
###
GET http://localhost:5000/barangKeluar/
###
GET http://localhost:5000/barangKeluar/
###
GET http://localhost:5000/barangMasuk/
###
GET http://localhost:5000/barangMasuk/
###
POST http://localhost:5000/barangKeluar
Content-Type: application/json

{
  "nama_barang": "Masker",
  "jenis_barang": "Barang Habis Pakai",
  "harga_barang": 5000,
  "jumlah_barang": 5,
  "kode_barang": "A001"
}

###
DELETE  http://localhost:5000/barangKeluar/52

###h
DELETE http://localhost:5000/barangMasuk/47

###
POST http://localhost:5000/barangMasuk
Content-Type: application/json

{
  "tanggal_masuk": "12/02/23",
  "jumlah_barang": 5,
  "kode_barang": "A001",
  "nama_barang": "Masker",
  "jenis_barang": "Barang Habis Pakai",
  "harga_barang": 2000
}

###
GET  http://localhost:5000/barangMasuk/

###
PATCH     http://localhost:5000/barangMasuk/51
Content-Type: application/json

{
  "tanggal_masuk": "2024-07-15",
  "jumlah_barang": 18,
  "kode_barang": "A001",
  "nama_barang": "Masker",
  "jenis_barang": "Habis Pakai"
}

###
DELETE  http://localhost:5000/barangKeluar/2

###
POST http://localhost:5000/peminjam
Content-Type: application/json

{
  "nama_barang": "Suntik",
  "jenis_barang": "Barang Habis Pakai",
  "harga_barang": 10000,
  "jumlah_barang": 1,
  "kode_barang": "A001",
  "tanggal_pinjam": "07/01/2024"
}

###
GET  http://localhost:5000/peminjam

###
PATCH     http://localhost:5000/peminjam/32
Content-Type: application/json

{
  "nama_barang": "Handskun",
  "jenis_barang": "Barang Habis Pakai",
  "harga_barang": 10000,
  "jumlah_barang": 1,
  "kode_barang": "A002",
  "tanggal_pinjam": "2024-07-17",
  "keterangan": "Rusak"
}


###
GET  http://localhost:5000/barang

###
POST   http://localhost:5000/barang
Content-Type: application/json

{
  "kode_barang": "A019",
  "nama_barang": "Suntik",
  "total_stock": 50,
  "jenis_barang": "baik",
  "harga_barang": 5000,
  "gambar_barang": "1715840066316-1711376166370-Face-mask 1.png"
}

###
PATCH    http://localhost:5000/barang/2
Content-Type: application/json

{
    "nama_barang": "Masker",
    "total_stock": 40,
    "jenis_barang": "Barang Habis Pakai",
    "harga_barang": 30000,
    "gambar_barang": "http://localhost:5000/uploads/1736078167113-1711423655652-suntik.jpg",
    "kode_barang": "A002"
}

###
DELETE   http://localhost:5000/barang/6

###
GET   http://localhost:5000/barang/

###
DELETE http://inventoryfkep-46301.portmap.io:46301/api/barang/7

###
PUT     http://localhost:5000/barang/A013
Content-Type: application/json

{
  "nama_barang": "Glove",
  "total_stock": 20,
  "jenis_barang": "buruk",
  "harga_barang": 5000,
  "gambar_barang": "1711375972357-Face-mask 1.png"
}

###
GET http://localhost:5000/dashboardNotif


###
GET http://localhost:5000/dashboardNotif


###
DELETE  http://localhost:5000/logout


###
POST   http://localhost:5000/register
Content-Type: application/json

{
    "username": "farel",
    "email": "farel@gmail.com",
    "password": "12345"
}


###
POST   http://localhost:5000/login
Content-Type: application/json

{
    "email": "farel@gmail.com",
    "password": "123"
}

###
PUT   http://localhost:5000/users/7
Content-Type: application/json

{
    "username": "ferel",
    "email": "farel@gmail.com",
    "role": "PURCHASEMANAGER"
}

###
PUT   https://inventoryfkepunklab.site/api/users/1
Content-Type: application/json

{
    "username": "dewi",
    "email": "dewi@gmail.com",
    "role": "ADMIN"
}

###
PATCH http://localhost:5000/changepass
Content-Type: application/json

{
  "email": "farel@gmail.com",
  "oldPassword": "12345",
  "newPassword": "123",
  "confirmPassword": "123"
}


###
GET   http://localhost:5000/users
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
POST  http://localhost:5000/forgotpass
Content-Type: application/json

{
  "email": "runtuwenedewi@gmail.com"
}

###
GET   http://localhost:5000/dataOrderBarang

###
PATCH     http://localhost:5000/cancelOrder/26

###
DELETE    http://localhost:5000/orderBarang/78

###
PATCH    http://localhost:5000/updateBarang/16

###
POST   http://localhost:5000/orderBarang/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

{
    "nama_matakuliah": "Hematologi 15",
    "prasat": "some prasat",
    "jam_praktek": "12:00",
    "tanggal_praktek": "26-2-2024",
    "tanggal_pengambilan": "2024-04-01T06:54:33.870Z",
    "tanggal_kembali_alat": "27-2-2024",
    "ruangan_lab": "GK1 202"
}

###
DELETE  http://localhost:5000/keranjang/40

###
GET   http://localhost:5000/keranjang
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
PATCH    http://localhost:5000/keranjang/61
Content-Type: application/json

{
  "jumlah_barang": 1
}

###
POST   http://localhost:5000/keranjang
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

{
  "jumlah_barang": 9,
  "barang": {
     "kode_barang": "A018",
        "nama_barang": "Suntik",
        "total_stock": 50,
        "jenis_barang": "baik",
        "harga_barang": 5000,
        "gambar_barang": "1715856034629-1711376166370-Face-mask 1.png"
  }
}

###
GET   http://localhost:5000/barang

###
GET   http://localhost:5000/peminjamBarang

###
PATCH    http://localhost:5000/peminjamBarang/5

###
PATCH    http://localhost:5000/peminjamBarang/2

###
POST   http://localhost:5000/prasat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

{
  "nama_prasat": "Kardio",
  "deskripsi": "Untuk anak kep",
  "barangDalamPrasat": [
    { "barangId": 1, "jumlah_barang": 10 },
    { "barangId": 4, "jumlah_barang": 10 }
  ]
}

###
PUT  http://localhost:5000/prasat/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

{
  "nama_prasat": "Kateter",
  "deskripsi": "coba aja",
  "created_by": 5,
  "barangDalamPrasat": [
    { "barangId": 1, "jumlah_barang": 0 },
    { "barangId": 1, "jumlah_barang": 0 }
  ]
}

###
GET  http://localhost:5000/prasat/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
DELETE   http://localhost:5000/prasat/2
Content-Type: application/json


###
POST   http://localhost:5000/preorderkeranjang
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

{
  "prasat": [
    { "id_prasat": 2 }
  ]
}

###
GET   http://localhost:5000/preorderkeranjang
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME


###
POST   http://localhost:5000/preorder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsIm5hbWUiOiJkZXdpZnIiLCJlbWFpbCI6ImRld2lmckBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzg2OTEyNSwiZXhwIjoxNzM2NDYxMTI1fQ.hT9AVcYSiV5xho04a0y3oEmJc2mwbbGotfsYwm4InWQ

{
  "rencana_pemakaian": "Mid to End",
  "jumlah_barang": 10
}

###
GET   http://localhost:5000/preorder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
GET   http://localhost:5000/allpreorder
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME


###
PATCH   http://localhost:5000/preorder/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
PATCH   http://localhost:5000/updateJumlahBarang/11
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

{
  "jumlah_barang": 3
}

###
GET   http://localhost:5000/prasat/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
POST    http://localhost:5000/preorderdetailbarang/
Content-Type: application/json

{
  "keterangan": "Pengadaan barang untuk semester genap"
}


###
GET   http://localhost:5000/preorderdetailbyprasat/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
GET   http://localhost:5000/barangpreoderapproveddekan/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
GET   http://localhost:5000/barangpreoderapprovedwarek1/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
GET   http://localhost:5000/barangpreoderapprovedwarek2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
GET   http://localhost:5000/barangpreoderapproved/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
PATCH   http://localhost:5000/databarangpreorderdekan/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
PATCH   http://localhost:5000/databarangpreorderwarek1/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME



###
PATCH   http://localhost:5000/databarangpreorderwarek2/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
PATCH   http://localhost:5000/barangsudahdibeli/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME

###
PATCH   http://localhost:5000/barangsudahditerima/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJkZXdpZiIsImVtYWlsIjoiZGV3aXIxMUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTczMzE1NjU5MCwiZXhwIjoxNzM1NzQ4NTkwfQ.spjuqP3-O2pi8tICGwTBbnqKVtbyYz9HgMzUpO69bME


###
GET   http://localhost:5000/sisabarang


###
GET   http://localhost:5000/barang



  {

    "nama_matakuliah": "Hematologi",
    "keranjangs": {
      "jumlah_barang": 7,
      "barangs": {
        "id_barang": "A013",
        "nama_barang": "Glove",
      }
    }
  },

{
  "nama_matakuliah": "Hematologi",
  "jumlah_barang": 7,
  "id_barang": "A013",
  "nama_barang": "Glove",
  "jumlah_barang": 7,
}
    



###
[
  {
    "id_barang": "A001",
    "nama_barang": "Glove",
    "matkuls": [
      {
        "nama_matakuliah": "Kardio",
        "jumlah_barang": "30"
      },
      {
        "nama_matakuliah": "Hematologi",
        "jumlah_barang": "30"
      }
    ]
  },
  {
    "id_barang": "A001",
    "nama_barang": "Glove",
    "matkuls": [
      {
        "nama_matakuliah": "Kardio",
        "jumlah_barang": "30"
      },
      {
        "nama_matakuliah": "Hematologi",
        "jumlah_barang": "30"
      }
    ]
  }
]

###
[
  {
    "id_peminjam": 75,
    "nama_dosen": "Dewi",
    "nama_matakuliah": "Kardio",
    "prasat": "S",
    "jam_praktek": "12.30",
    "tanggal_praktek": "2024-04-30",
    "tanggal_pengambilan": "2024-04-30T02:13:20.334Z",
    "keranjangs": {
      "jumlah_barang": 1,
      "barangs": {
        "id_barang": "A001",
        "nama_barang": "Suntik",
        "total_stock": 14,
        "jenis_barang": "Habis Pakai",
        "harga_barang": 5000,
        "gambar_barang": "1714378258031-1711423655652-suntik.jpg"
      },
      "jumlah_barang": 2,
      "barangs": {
        "id_barang": "A003",
        "nama_barang": "Masker",
        "total_stock": 9,
        "jenis_barang": "Habis Pakai",
        "harga_barang": 5000,
        "gambar_barang": "1714379192328-1711378417244-Face-mask 1.png"
      }
    }
  },
]



###

[
  {
    "nama_dosen": "Dewi",
    "nama_matakuliah": "Kardio",
    "prasat": "some prasat",
    "jam_praktek": "12:00",
    "tanggal_praktek": "26-2-2024",
    "keranjangs": [
      {
        "jumlah_pemesanan": 1,
        "barangs": {
          "id_barang": "A001",
          "nama_barang": "Glove",
          "total_stock": 10,
          "jenis_barang": "habis pakai",
          "gambar_barang": "1714379192328-1711378417244-Face-mask 1.png"
        }
      },
      {
        "jumlah_pemesanan": 1,
        "barangs": {
          "id_barang": "A002",
          "nama_barang": "Mask",
          "total_stock": 20,
          "jenis_barang": "habis pakai",
          "gambar_barang": "1714379192328-1711378417244-Face-mask 1.png"
        }
      },
    ]
  }
]